remote_theme: eecs485staff/primer-spec
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jemoji
kramdown:
  input: GFM
readme_index:
  remove_originals: true
  with_frontmatter: true

# Primer-specific settings
defaults:
  - scope:
      path: ""
    values:
      primer:
        theme: "dark" # Options: light, dark, auto